### ISSUE TITLE
Issue with SQL & error message

### ISSUE THREAD

**Issue by cocoabythefire** [wbyoung/azul#11]
I accidentally did this at one point:

```js
var Token = db.model('token');
var token = Token.create({
  value: 'abc1234',
});
token.save();
```

I tracked this down to Azul generating this invalid SQL which it sent to the database without really complaining that I did something wrong:

```sql
INSERT INTO "tokens" () VALUES () RETURNING "id"
```

The result was this error message (which wasn't all that helpful):

```
error: syntax error at or near ")"
  at Connection.parseE (/Users/bntarvin/Code/glitter/node_modules/pg/lib/connection.js:534:11)
  at Connection.parseMessage (/Users/bntarvin/Code/glitter/node_modules/pg/lib/connection.js:361:17)
  at Socket.<anonymous> (/Users/bntarvin/Code/glitter/node_modules/pg/lib/connection.js:105:22)
```

**Comment by wbyoung** [comment]
Good find, thanks! That should certainly generate a better error message.

**Comment by wbyoung** [comment]
This will now throw the following error:

_Token has no attributes. Please make sure your model is properly defined._

Would that message have made it easier to figure out what was wrong in your setup here? Could it be worded any better?

**Comment by cocoabythefire** [comment]
yes that is much more helpful, thanks!
