### ISSUE TITLE
Problem with assigning objects as value in create parameters 

### ISSUE THREAD

**Issue by cocoabythefire** [wbyoung/azul#12]
I expect the following to work.
```js
var user = User.create({ name: 'Brit' });
var token = Token.create({ value: 'abc1234', user: user });
user.save().then(function() { return token.save(); })
```
But it turns out that assigning user: user in the create does not actually do anything. The user is still undefined.

**Comment by wbyoung** [comment]
This should be fixed as of 39a2a77 and query support in d67ca71. Both of theses were release in [v0.0.1-alpha.9](https://github.com/wbyoung/azul/tree/v0.0.1-alpha.9). Can you check if you're using that version & see if this works for you now?

**Comment by cocoabythefire** [comment]
It still doesn't work for me with alpha 9 :(

**Comment by wbyoung** [comment]
Can you a full example script?

**Comment by cocoabythefire** [comment]
cocoabythefire / gist:17c21e7a3013b3704d3e

**Comment by wbyoung** [comment]
It looks like this will work and save both:

```js
var user = User.create({ name: 'Brit' });
var token = Token.create({ value: 'abc1234', user: user });
token.save().then(function() {
  // both saved
});
```

I'll try to get that other one fixed.
