### ISSUE TITLE
Save doesn't resolve to anything

### ISSUE THREAD

**Issue by cocoabythefire** [wbyoung/azul#13]
It doesn't seem like save resolves to anything but I would expect it to return the saved object.

```js
article.save().then(function(value) {
  // value should probably be article
})

**Comment by wbyoung** [comment]
It certainly [looks like it does](https://github.com/wbyoung/azul/blob/5df01b42a08a8fc25f6c476b1a6bde2d07366b1e/lib/model/model.js#L486). Can you post a [gist](https://gist.github.com/) of this or an example project with migrations?

**Comment by cocoabythefire** [comment]
cocoabythefire / gist:17c21e7a3013b3704d3e

**Comment by wbyoung** [comment]
In fact, [there's a test for it](https://github.com/wbyoung/azul/blob/59a7bb28156ffe8909c46101ea421aa752387f76/test/model/model_tests.js#L528).

I'm going to close this for now, but if you can reproduce this in the currently released version, please re-open it. It certainly wouldn't be good if this bug existed.
