### ISSUE TITLE
Custom tableName on relation is blown away in hasMany

### ISSUE THREAD

**Issue by tgriesser** [wbyoung/azul#24]
Neat project. I was looking through trying it out and ran into this issue: 

If a model defines a custom `tableName` and then that model is subsequently used as the target of a `hasMany`, the custom `tableName` is blown away. The culprit looks to be this line [here](https://github.com/wbyoung/azul/blob/75bee04055568f2ad3d7137d04d38855b3ecc1a3/lib/relations/has_many_through.js#L437), if the `db.model(name)` resolves the existing model instance, it will then mutate the `tableName` you've already defined elsewhere.

I had trouble following the class hierarchy, so I figured you might have a better idea of where/how a fix could take place.

One other thing that seemed to be missing which would be nice is a method or property containing all loaded relations on the current model (for convenience in toJSON)

**Comment by wbyoung** [comment]
Thanks. I used your Bookshelf a bit, but it wasn't quite what I wanted, but it was very close. Thanks for creating it!

I just started a new job, so I haven't been working on this quite as much recently, but that issue is on a TODO list that I have personally.

As for the method/property for JSON, does [`json`](http://www.azuljs.com/guides/models/#methods-properties-json) do what you want?

I hesitant to a method that includes the loaded relations since that will return different information based on what has actually been loaded. While convenient, I think the model specifying exactly what's required to convert to JSON will lead to better for users in the long run.

**Comment by tgriesser** [comment]
> Thanks. I used your Bookshelf a bit, but it wasn't quite what I wanted, but it was very close. Thanks for creating it!

Thanks! Glad to hear that!

> I just started a new job, so I haven't been working on this quite as much recently

Know the feeling, open source can be tough when life gets in the way :)

> I just started a new job, so I haven't been working on this quite as much recently, but that issue is on a TODO list that I have personally.

Cool, well +1 on that then, a friend of mine is using this on a project and wanted me to take a look at why the relation thing might not be working and that's when I came across it.

> While convenient, I think the model specifying exactly what's required to convert to JSON will lead to better for users in the long run.

Totally valid point. I guess what seemed to be missing was a way to determine what relations were loaded, if any all... for example:

```js
toJSON() {
  return {
    ...this.toObject(), 
    ...this.loadedRelations
  }
}
```

If you try to access a relation but it hasn't been loaded yet it throws, so instead I needed to access via the `_${relationName}` syntax like so:

```js
  toJSON() {
    return {
      ...this.toObject(),
      location: this._location,
      tickets: this._tickets
    };
  }
```

Btw, looks like you did a great job separating out the query builder [maguey](https://github.com/wbyoung/maguey) any chance you plan on adding docs for that? Seems like it's JSDoc'ed really well.

Also ping @tkellen / @ashleygwilliams - ya'll might interested in this project. I plan on getting back into the loop with knex/bookshelf and the hundreds of tickets I haven't had a chance to address over the last couple months, but this lib also seems to have made some great design decisions and while I haven't dug in too deep it looks like it might also be a good fit for any endpoints / associated model heavy node projects.

**Comment by wbyoung** [comment]
@tgriesser no plans to document `maguey` just yet, though [the basic data queries](http://www.azuljs.com/guides/queries/#data-queries) are pretty close to what you'd do with `maguey`.

I'm having a hard time thinking of scenarios where you'd want to figure out what associates have been loaded yet. I guess it's just a coding style thing, but I'd prefer to know that a function that receives a model is receiving the model with all the associations loaded that it expects to be loaded.

I'll keep that in mind, though, and hopefully we can get something exposed for it.

**Comment by wbyoung** [comment]
@tgriesser this should be fixed in master. Please give it a try and let me know if you were having a different issue. [The test added here](https://github.com/wbyoung/azul/commit/860197318f9a1ca79970b2d053351e44e810b1ef) is what I believe your model configuration looked like.
